---

- name: enable centos-release-opstools
  package:
    state: present
    name: centos-release-opstools

- name: deploy collectd
  package:
    state: present
    name: '{{ item }}'
  with_items:
    - collectd-disk

- name: place networking config
  template:
    src: 10-network-write.conf.j2
    dest: "/etc/collectd.d/10-network-write.conf"


- name: set sebool for collectd networking
  seboolean:
    name: collectd_tcp_network_connect
    state: yes
    persistent: yes
  when: '"{{ ansible_selinux.mode }}" in ["enforcing", "permissive"]'

- name: start collectd
  service:
    name: collectd
    state: started
    enabled: yes

